//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.24 at 07:42:15 PM CDT 
//

//@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sat.gob.mx/cfd/3", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sat.gob.mx/cfd/3",  
    xmlns = { 
        @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://www.sat.gob.mx/cfd/3", prefix = "cfdi"),  
        @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://www.w3.org/2001/XMLSchema-instance", prefix = "xsi")
    },  
    elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)

package cfdihjk.cfdv32;
